name: linters

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        # INSTALLS
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "PYTHONPATH=/home/runner/work/ai-economist-opensource/ai-economist-opensource/" >> $GITHUB_ENV

    - name: Sort imports with isort
      run: |
        # isort config compatible with black
        isort --multi-line=3 --trailing-comma --force-grid-wrap=0 --use-parentheses --line-width=88  --check-only -rc ai_economist/
      continue-on-error: false

    - name: Format code with black
      run: |
        black --line-length 88 --check ai_economist/
      continue-on-error: false

    - name: Lint code with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 --count --select=E9,F63,F7,F82 --show-source --statistics ai_economist 